=== mri786/AVDSnippets/schemas/avd_hostpool.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "LBG multi-session host pool",
    "description": "An LBG multi-session host pool configuration",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "JSON schema reference"
        },
        "metadata": {
            "type": "object",
            "description": "Additional unstructured metadata to include with the template deployment.",
            "additionalProperties": true
        },
        "businessUnitName": {
            "type": "string",
            "description": "Business Unit Name",
            "minLength": 1
        },
        "location": {
            "type": "string",
            "description": "Azure location",
            "enum": [
                "uksouth"
            ],
            "default": "uksouth"
        },
        "labId": {
            "type": "string",
            "description": "VDI lab id",
            "pattern": "[a-z]\\d{2}[a-b]$"
        },
        "hostpool": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "description": "Two digit host pool id number",
                    "pattern": "^\\d{2}$"
                },
                "rdpProperties": {
                    "type": "string",
                    "description": "RDP Properties reference from RDPProperties lookup file",
                    "pattern": "^MULT-\\w+$"
                },
                "maxSessionLimit": {
                    "type": "integer",
                    "description": "Maximum user sessions per host",
                    "minimum": 5,
                    "maximum": 25,
                    "default": 15
                },
                "prefferedappGroupType": {
                    "type": "string",
                    "description": "The type of preferred application group type",
                    "enum": [
                        "Desktop",
                        "RailApplications",
                        "None"
                    ],
                    "default": "Desktop"
                },
                "agentUpdate": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string",
                            "description": "The type of maintenance for session host components",
                            "enum": [
                                "Default",
                                "Scheduled"
                            ],
                            "default": "Scheduled"
                        },
                        "useSessionHostLocalTime": {
                            "type": "boolean",
                            "description": "Whether to use localTime of the virtual machine",
                            "default": false
                        },
                        "maintenanceWindowTimeZone": {
                            "type": "string",
                            "description": "Time zone for maintenance as defined in .net system.timezoneinfo",
                            "enum": [
                                "GMT Standard Time"
                            ],
                            "default": "GMT Standard Time"
                        },
                        "maintenanceWindows": {
                            "type": "object",
                            "properties": {
                                "hour": {
                                    "type": "integer",
                                    "description": "The update start hour of the day. (0 - 23)",
                                    "minimum": 0,
                                    "maximum": 23
                                },
                                "dayOfWeek": {
                                    "type": "string",
                                    "description": "Day of week",
                                    "enum": [
                                        "Monday",
                                        "Tuesday",
                                        "Wednesday",
                                        "Thursday",
                                        "Friday",
                                        "Saturday",
                                        "Sunday"
                                    ]
                                }
                            },
                            "required": [
                                "hour",
                                "dayOfWeek"
                            ]
                        }
                    },
                    "required": [
                        "type",
                        "useSessionHostLocalTime",
                        "maintenanceWindowTimeZone",
                        "maintenanceWindows"
                    ]
                }
            },
            "required": [
                "id",
                "rdpProperties",
                "maxSessionLimit",
                "prefferedappGroupType",
                "agentUpdate"
            ]
        },
        "appGroup": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "description": "Resource Type of ApplicationGroup",
                    "enum": [
                        "Desktop",
                        "RemoteApp"
                    ],
                    "default": "Desktop"
                }
            },
            "required": [
                "type"
            ]
        },
        "sessionHosts": {
            "type": "object",
            "properties": {
                "haadj": {
                    "type": "boolean",
                    "description": "Whether to hybrid AD join the session hosts"
                },
                "timeZone": {
                    "type": "string",
                    "description": "Specifies the time zone of the virtual machine as defined in .net system.timezoneinfo",
                    "enum": [
                        "GMT Standard Time"
                    ],
                    "default": "GMT Standard Time"
                },
                "buildImage": {
                    "type": "string",
                    "description": "Computer gallery image name to use for session hosts"
                },
                "buildImageVer": {
                    "type": "string",
                    "description": "Version number of Computer gallery image"
                },
                "securityClassification": {
                    "type": "string",
                    "description": "LBG security classification to tag sessions hosts",
                    "enum": [
                        "Highly Confidential",
                        "Confidential",
                        "Limited"
                    ],
                    "default": "Confidential"
                },
                "vmSku": {
                    "type": "string",
                    "description": "Azure VM SKU to use for session hosts"
                },
                "vmDiskType": {
                    "type": "string",
                    "description": "Azure managed disk type to use for session hosts",
                    "enum": [
                        "Premium_LRS"
                    ],
                    "default": "Premium_LRS"
                },
                "vmDiskSizeGb": {
                    "type": "integer",
                    "maximum": 1023,
                    "enum": [
                        128
                    ],
                    "default": 128
                },
                "localAdminUsername": {
                    "type": "string",
                    "description": "Name to set built-in administrator account",
                    "default": "mshadmin"
                }
            },
            "required": [
                "haadj",
                "timeZone",
                "buildImage",
                "buildImageVer",
                "securityClassification",
                "vmSku",
                "vmDiskType",
                "vmDiskSizeGb",
                "localAdminUsername"
            ]
        }
    },
    "required": [
        "$schema",
        "businessUnitName",
        "location",
        "hostpool",
        "appGroup",
        "sessionHosts"
    ]
}

=== mri786/AVDSnippets/params/hostpools/uks-EEE-vdi-avd-hpl-mult-003-01.json
{
    "$schema": "../../../schemas/avd_hostpool.json",
    "businessUnitName": "ReleaseOneDev",
    "location": "uksouth",
    "labId": "v01a",
    "hostpool": {
        "id": "01",
        "rdpProperties": "MULT-copypaste",
        "maxSessionLimit": 15,
        "prefferedappGroupType": "Desktop",
        "agentUpdate": {
            "type": "Scheduled",
            "useSessionHostLocalTime": false,
            "maintenanceWindowTimeZone": "GMT Standard Time",
            "maintenanceWindows": {
                "hour": 1,
                "dayOfWeek": "Saturday"
            }
        }
    },
    "appGroup": {
        "type": "Desktop"
    },
    "sessionHosts": {
        "haadj": true,
        "timeZone": "GMT Standard Time",
        "buildImage": "uks-img-windows-desktop-11-gen2-22h2ent-mult-888",
        "buildImageVer": "1.37.1677598566",
        "securityClassification": "Confidential",
        "vmSku": "standard_D8s_v3",
        "vmDiskType": "Premium_LRS",
        "vmDiskSizeGb": 128,
        "localAdminUsername": "mshadmin"
    }
}
